export const blockchains = [
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Celo",
    slug: "celo",
    apiSlug: "celo",
    icon: "/blockchains/celo.svg",
    placeholder: "0x... address",
    coin: "CELO",
    contractAddress: "0x71D724EaF572Cf1bc3b1d0871D3D912B2597De58",
    chainId: 42220,
    networkData: {
      chainId: "0xa4ec",
      chainName: "Celo Mainnet",
      nativeCurrency: {
        name: "CELO",
        symbol: "CELO",
        decimals: 18,
      },
      rpcUrls: ["https://forno.celo.org"],
      blockExplorerUrls: ["https://celoscan.io"],
    },
  },
  {
    group: "eco",
    groupLabel: "Eco",
    item: "Celo",
    slug: "celo_eco",
    apiSlug: "celo",
    icon: "/blockchains/celo.svg",
    placeholder: "0x... address",
    coin: "CELO",
    contractAddress: "0x63A6B87E920E8940006CF77b3d3aAbCC63F91B2B",
    ecoTokenAddress: "0x9995cc8f20db5896943afc8ee0ba463259c931ed",
    chainId: 42220,
    networkData: {
      chainId: "0xa4ec",
      chainName: "Celo Mainnet",
      nativeCurrency: {
        name: "CELO",
        symbol: "CELO",
        decimals: 18,
      },
      rpcUrls: ["https://forno.celo.org"],
      blockExplorerUrls: ["https://celoscan.io"],
    },
  },
];
